CREATE TABLE agent_session (
    session_key          VARCHAR(80) PRIMARY KEY,
    display_name         VARCHAR(200) NOT NULL,
    provider             VARCHAR(50) NOT NULL,
    external_session_id  VARCHAR(200),
    status               VARCHAR(20) NOT NULL,
    last_verified_at     TIMESTAMPTZ,
    version              BIGINT NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL,
    updated_at           TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_agent_session_status
        CHECK (status IN ('UNBOUND', 'READY', 'VERIFYING', 'INVALID')),
    CONSTRAINT chk_agent_session_version CHECK (version >= 0)
);

CREATE UNIQUE INDEX uq_agent_session_external_id
    ON agent_session (provider, external_session_id)
    WHERE external_session_id IS NOT NULL;

CREATE TABLE dispatcher_lane (
    lane_key                   VARCHAR(80) PRIMARY KEY,
    state                      VARCHAR(20) NOT NULL,
    active_run_id              UUID,
    fencing_token              BIGINT NOT NULL DEFAULT 0,
    observed_first_pending_at  TIMESTAMPTZ,
    observed_last_pending_at   TIMESTAMPTZ,
    eligible_at                TIMESTAMPTZ,
    retry_not_before           TIMESTAMPTZ,
    consecutive_failure_count  INTEGER NOT NULL DEFAULT 0,
    last_error_code            VARCHAR(100),
    paused_reason              VARCHAR(300),
    version                    BIGINT NOT NULL DEFAULT 0,
    created_at                 TIMESTAMPTZ NOT NULL,
    updated_at                 TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_dispatcher_lane_state
        CHECK (state IN ('IDLE', 'WAITING', 'STARTING', 'RUNNING', 'RECOVERING', 'PAUSED')),
    CONSTRAINT chk_dispatcher_lane_fencing_token CHECK (fencing_token >= 0),
    CONSTRAINT chk_dispatcher_lane_failure_count CHECK (consecutive_failure_count >= 0),
    CONSTRAINT chk_dispatcher_lane_version CHECK (version >= 0),
    CONSTRAINT chk_dispatcher_lane_active_run
        CHECK ((state IN ('IDLE', 'WAITING') AND active_run_id IS NULL)
            OR (state IN ('STARTING', 'RUNNING', 'RECOVERING') AND active_run_id IS NOT NULL)
            OR state = 'PAUSED')
);

CREATE TABLE dispatcher_run (
    run_id                    UUID PRIMARY KEY,
    lane_key                  VARCHAR(80) NOT NULL REFERENCES dispatcher_lane (lane_key),
    run_sequence              BIGINT NOT NULL,
    fencing_token             BIGINT NOT NULL,
    status                    VARCHAR(30) NOT NULL,
    session_key               VARCHAR(80) NOT NULL REFERENCES agent_session (session_key),
    external_execution_id     VARCHAR(200),
    starter_instance_id       VARCHAR(200) NOT NULL,
    event_count               INTEGER NOT NULL,
    start_requested_at        TIMESTAMPTZ NOT NULL,
    started_at                TIMESTAMPTZ,
    last_heartbeat_at         TIMESTAMPTZ,
    heartbeat_deadline        TIMESTAMPTZ,
    finished_at               TIMESTAMPTZ,
    result_code               VARCHAR(100),
    last_error_code           VARCHAR(100),
    recovery_attempt_count    INTEGER NOT NULL DEFAULT 0,
    created_at                TIMESTAMPTZ NOT NULL,
    updated_at                TIMESTAMPTZ NOT NULL,
    CONSTRAINT uq_dispatcher_run_sequence UNIQUE (lane_key, run_sequence),
    CONSTRAINT uq_dispatcher_run_fencing_token UNIQUE (lane_key, fencing_token),
    CONSTRAINT chk_dispatcher_run_status
        CHECK (status IN ('STARTING', 'RUNNING', 'SUCCEEDED', 'FAILED',
                          'START_REJECTED', 'OUTCOME_UNKNOWN')),
    CONSTRAINT chk_dispatcher_run_sequence CHECK (run_sequence > 0),
    CONSTRAINT chk_dispatcher_run_fencing_token CHECK (fencing_token > 0),
    CONSTRAINT chk_dispatcher_run_event_count CHECK (event_count > 0),
    CONSTRAINT chk_dispatcher_run_recovery_count CHECK (recovery_attempt_count >= 0)
);

CREATE UNIQUE INDEX uq_dispatcher_single_active_run
    ON dispatcher_run ((TRUE))
    WHERE status IN ('STARTING', 'RUNNING', 'OUTCOME_UNKNOWN');

ALTER TABLE dispatcher_lane
    ADD CONSTRAINT fk_dispatcher_lane_active_run
        FOREIGN KEY (active_run_id) REFERENCES dispatcher_run (run_id)
        DEFERRABLE INITIALLY DEFERRED;

CREATE TABLE trigger_cursor (
    source_key       VARCHAR(100) PRIMARY KEY,
    cursor_value     TEXT,
    last_polled_at   TIMESTAMPTZ,
    version          BIGINT NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL,
    updated_at       TIMESTAMPTZ NOT NULL,
    CONSTRAINT chk_trigger_cursor_version CHECK (version >= 0)
);

CREATE TABLE dispatcher_event (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key            VARCHAR(100) NOT NULL REFERENCES trigger_cursor (source_key),
    source_event_id       VARCHAR(200) NOT NULL,
    trigger_type          VARCHAR(100) NOT NULL,
    subject_ref           VARCHAR(500) NOT NULL,
    schema_version        INTEGER NOT NULL,
    occurred_at           TIMESTAMPTZ NOT NULL,
    recorded_at           TIMESTAMPTZ NOT NULL,
    processing_state      VARCHAR(20) NOT NULL,
    active_run_id         UUID REFERENCES dispatcher_run (run_id),
    consumed_by_run_id    UUID REFERENCES dispatcher_run (run_id),
    consumed_at           TIMESTAMPTZ,
    metadata              JSONB NOT NULL DEFAULT '{}'::jsonb,
    CONSTRAINT uq_dispatcher_event_source UNIQUE (source_key, source_event_id),
    CONSTRAINT chk_dispatcher_event_schema_version CHECK (schema_version > 0),
    CONSTRAINT chk_dispatcher_event_state
        CHECK ((processing_state = 'PENDING'
                    AND active_run_id IS NULL
                    AND consumed_by_run_id IS NULL
                    AND consumed_at IS NULL)
            OR (processing_state = 'CLAIMED'
                    AND active_run_id IS NOT NULL
                    AND consumed_by_run_id IS NULL
                    AND consumed_at IS NULL)
            OR (processing_state = 'CONSUMED'
                    AND active_run_id IS NULL
                    AND consumed_by_run_id IS NOT NULL
                    AND consumed_at IS NOT NULL))
);

CREATE INDEX idx_dispatcher_event_pending
    ON dispatcher_event (recorded_at, id)
    WHERE processing_state = 'PENDING';

CREATE INDEX idx_dispatcher_event_active_run
    ON dispatcher_event (active_run_id)
    WHERE active_run_id IS NOT NULL;

CREATE TABLE dispatcher_run_event (
    run_id       UUID NOT NULL REFERENCES dispatcher_run (run_id),
    event_id     BIGINT NOT NULL REFERENCES dispatcher_event (id),
    position     INTEGER NOT NULL,
    created_at   TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (run_id, event_id),
    CONSTRAINT uq_dispatcher_run_event_position UNIQUE (run_id, position),
    CONSTRAINT chk_dispatcher_run_event_position CHECK (position > 0)
);

INSERT INTO agent_session (
    session_key, display_name, provider, status, version, created_at, updated_at)
VALUES (
    'development-main', '開發主要對話', 'CODEX_DESKTOP', 'UNBOUND', 0,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO dispatcher_lane (
    lane_key, state, fencing_token, consecutive_failure_count, version,
    created_at, updated_at)
VALUES (
    'CODEX_DEVELOPMENT', 'IDLE', 0, 0, 0,
    CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO trigger_cursor (
    source_key, cursor_value, version, created_at, updated_at)
VALUES (
    'main-conversation-feed-v1', NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
