package com.aproject.aidriven.mymobilesecretary.booking.domain;

public enum AuthorizationFailure {
    WORKSPACE_MISMATCH,
    ACTOR_MISMATCH,
    AUTHORIZATION_EXPIRED,
    OFFER_MISMATCH,
    ORDER_MISMATCH,
    PROVIDER_MISMATCH,
    ENVIRONMENT_MISMATCH,
    TRAVELLER_MISMATCH,
    INVENTORY_UNAVAILABLE,
    STALE_QUOTE,
    CAPABILITY_UNSUPPORTED,
    PRICE_EXCEEDED,
    CURRENCY_MISMATCH,
    TERMS_CHANGED,
    NON_REFUNDABLE_NOT_ACCEPTED
}
