CREATE TABLE conversation_voice_profile (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    assistant_self_name VARCHAR(96),
    user_address VARCHAR(96),
    praise_variant_cursor INTEGER NOT NULL DEFAULT -1,
    dissatisfaction_variant_cursor INTEGER NOT NULL DEFAULT -1,
    revision BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    workspace_id UUID NOT NULL,
    created_by_user_id UUID NOT NULL,
    CONSTRAINT uq_conversation_voice_profile_actor
        UNIQUE (workspace_id, created_by_user_id),
    CONSTRAINT chk_conversation_voice_profile_names CHECK (
        (assistant_self_name IS NULL OR (
            length(btrim(assistant_self_name)) BETWEEN 1 AND 96
            AND assistant_self_name !~ '[[:cntrl:]]'))
        AND (user_address IS NULL OR (
            length(btrim(user_address)) BETWEEN 1 AND 96
            AND user_address !~ '[[:cntrl:]]'))),
    CONSTRAINT chk_conversation_voice_profile_cursors CHECK (
        praise_variant_cursor >= -1 AND dissatisfaction_variant_cursor >= -1),
    CONSTRAINT chk_conversation_voice_profile_revision CHECK (revision > 0)
);

ALTER TABLE conversation_voice_profile ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_voice_profile FORCE ROW LEVEL SECURITY;
CREATE POLICY rls_conversation_voice_profile_actor
    ON conversation_voice_profile FOR ALL
    USING (app_workspace_matches(workspace_id) AND app_actor_matches(created_by_user_id))
    WITH CHECK (app_workspace_matches(workspace_id) AND app_actor_matches(created_by_user_id));

ALTER TABLE conversation_repair_draft
    DROP CONSTRAINT chk_conversation_repair_kind;
ALTER TABLE conversation_repair_draft
    ADD CONSTRAINT chk_conversation_repair_kind CHECK (repair_kind IN (
        'CROSS_DOMAIN_RELATIONSHIP', 'REPEATED_QUESTION', 'FORMAT', 'WRONG_ANSWER',
        'DISSATISFACTION'));

ALTER TABLE conversation_pending_question
    DROP CONSTRAINT chk_conversation_pending_question_status;
ALTER TABLE conversation_pending_question
    ADD CONSTRAINT chk_conversation_pending_question_status CHECK (
        status IN ('PENDING', 'SUSPENDED', 'ANSWERED', 'CANCELED', 'EXPIRED'));
ALTER TABLE conversation_pending_question
    ADD CONSTRAINT uq_conversation_pending_question_owned_id
        UNIQUE (id, workspace_id, created_by_user_id);

ALTER TABLE conversation_repair_draft
    ADD COLUMN suspended_question_id UUID;
ALTER TABLE conversation_repair_draft
    ADD CONSTRAINT fk_conversation_repair_suspended_question FOREIGN KEY (
        suspended_question_id, workspace_id, created_by_user_id)
        REFERENCES conversation_pending_question (id, workspace_id, created_by_user_id);

CREATE TABLE conversation_voice_preference_draft (
    id UUID PRIMARY KEY,
    channel VARCHAR(40) NOT NULL,
    conversation_scope_digest VARCHAR(64) NOT NULL,
    scope_key_version INTEGER NOT NULL,
    target VARCHAR(32) NOT NULL,
    assistant_self_name VARCHAR(96),
    user_address VARCHAR(96),
    suspended_question_id UUID,
    status VARCHAR(20) NOT NULL,
    revision BIGINT NOT NULL,
    expires_at TIMESTAMPTZ NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    workspace_id UUID NOT NULL,
    created_by_user_id UUID NOT NULL,
    CONSTRAINT chk_conversation_voice_draft_scope CHECK (
        conversation_scope_digest ~ '^[0-9a-f]{64}$' AND scope_key_version > 0),
    CONSTRAINT chk_conversation_voice_draft_target CHECK (
        target IN ('UNDECIDED', 'ASSISTANT_NAME', 'USER_ADDRESS', 'BOTH')),
    CONSTRAINT chk_conversation_voice_draft_status CHECK (
        status IN ('PENDING', 'COMPLETED', 'CANCELED', 'EXPIRED')),
    CONSTRAINT chk_conversation_voice_draft_values CHECK (
        (assistant_self_name IS NULL OR (
            length(btrim(assistant_self_name)) BETWEEN 1 AND 96
            AND assistant_self_name !~ '[[:cntrl:]]'))
        AND (user_address IS NULL OR (
            length(btrim(user_address)) BETWEEN 1 AND 96
            AND user_address !~ '[[:cntrl:]]'))),
    CONSTRAINT chk_conversation_voice_draft_revision CHECK (revision > 0),
    CONSTRAINT chk_conversation_voice_draft_expiry CHECK (expires_at > created_at),
    CONSTRAINT fk_conversation_voice_draft_suspended_question FOREIGN KEY (
        suspended_question_id, workspace_id, created_by_user_id)
        REFERENCES conversation_pending_question (id, workspace_id, created_by_user_id)
);

CREATE UNIQUE INDEX uq_conversation_voice_draft_pending_scope
    ON conversation_voice_preference_draft (
        workspace_id, created_by_user_id, channel, conversation_scope_digest)
    WHERE status = 'PENDING';

ALTER TABLE conversation_voice_preference_draft ENABLE ROW LEVEL SECURITY;
ALTER TABLE conversation_voice_preference_draft FORCE ROW LEVEL SECURITY;
CREATE POLICY rls_conversation_voice_preference_draft_actor
    ON conversation_voice_preference_draft FOR ALL
    USING (app_workspace_matches(workspace_id) AND app_actor_matches(created_by_user_id))
    WITH CHECK (app_workspace_matches(workspace_id) AND app_actor_matches(created_by_user_id));
