CREATE TABLE actor_location_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    location_kind VARCHAR(20) NOT NULL,
    place_id BIGINT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    revision BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    workspace_id UUID NOT NULL,
    created_by_user_id UUID NOT NULL,
    CONSTRAINT uq_actor_location_preference_kind
        UNIQUE (workspace_id, created_by_user_id, location_kind),
    CONSTRAINT chk_actor_location_preference_kind
        CHECK (location_kind IN ('HOME')),
    CONSTRAINT chk_actor_location_preference_revision
        CHECK (revision > 0),
    CONSTRAINT fk_actor_location_preference_owned_place FOREIGN KEY (
        place_id, workspace_id, created_by_user_id)
        REFERENCES place (id, workspace_id, created_by_user_id)
);

ALTER TABLE actor_location_preference ENABLE ROW LEVEL SECURITY;
ALTER TABLE actor_location_preference FORCE ROW LEVEL SECURITY;

CREATE POLICY rls_actor_location_preference_actor
    ON actor_location_preference FOR ALL
    USING (
        app_workspace_matches(workspace_id)
        AND app_actor_matches(created_by_user_id))
    WITH CHECK (
        app_workspace_matches(workspace_id)
        AND app_actor_matches(created_by_user_id));
