CREATE TABLE actor_route_operation_preference (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    general_before_minutes INTEGER,
    general_after_minutes INTEGER,
    parking_minutes INTEGER,
    ride_hail_wait_minutes INTEGER,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    revision BIGINT NOT NULL,
    version BIGINT NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    workspace_id UUID NOT NULL,
    created_by_user_id UUID NOT NULL,
    CONSTRAINT uq_actor_route_operation_preference
        UNIQUE (workspace_id, created_by_user_id),
    CONSTRAINT chk_actor_route_operation_preference_general_before
        CHECK (general_before_minutes IS NULL
            OR general_before_minutes BETWEEN 0 AND 240),
    CONSTRAINT chk_actor_route_operation_preference_general_after
        CHECK (general_after_minutes IS NULL
            OR general_after_minutes BETWEEN 0 AND 240),
    CONSTRAINT chk_actor_route_operation_preference_parking
        CHECK (parking_minutes IS NULL OR parking_minutes BETWEEN 0 AND 240),
    CONSTRAINT chk_actor_route_operation_preference_ride_hail_wait
        CHECK (ride_hail_wait_minutes IS NULL
            OR ride_hail_wait_minutes BETWEEN 0 AND 240),
    CONSTRAINT chk_actor_route_operation_preference_revision
        CHECK (revision > 0)
);

ALTER TABLE actor_route_operation_preference ENABLE ROW LEVEL SECURITY;
ALTER TABLE actor_route_operation_preference FORCE ROW LEVEL SECURITY;

CREATE POLICY rls_actor_route_operation_preference_actor
    ON actor_route_operation_preference FOR ALL
    USING (
        app_workspace_matches(workspace_id)
        AND app_actor_matches(created_by_user_id))
    WITH CHECK (
        app_workspace_matches(workspace_id)
        AND app_actor_matches(created_by_user_id));
